name: krishi_saathi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0  # Make sure this line is present
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.3  
  local_auth: ^2.1.6
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env  # Make sure this line is present