name: krishi_saathi
description: "Your Smart Farming Companion - A comprehensive agriculture management app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Firebase & Authentication (Downgraded to working versions)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.7.4
  google_sign_in: ^6.3.0
  
  # Local Storage & Caching
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Location & Maps
  geolocator: ^13.0.4
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  location: ^7.0.1
  
  # Media & Images
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  photo_view: ^0.15.0
  flutter_image_compress: ^2.3.0
  
  # Permissions
  permission_handler: ^11.4.0
  
  # UI Components & Animations
  lottie: ^3.1.2
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  
  # Charts & Graphs (for farming data)
  fl_chart: ^0.69.2
  syncfusion_flutter_charts: ^26.2.14
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.0
  equatable: ^2.0.5
  connectivity_plus: ^6.1.5
  device_info_plus: ^10.1.2
  package_info_plus: ^8.3.1
  
  # Weather API
  weather: ^3.1.1
  
  # Notifications
  flutter_local_notifications: ^17.2.4
  
  # File Handling
  file_picker: ^8.3.7
  open_file: ^3.5.3
  
  # Logging & Development
  logger: ^2.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Quality
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env